### ISSUE TITLE
Feature request: new commandline parameter

### ISSUE THREAD

**Issue by airathere** [NETWAYS/check_sophos_central#6]
Hi all,

first of: thanks for the useful plugin!
I would like to ask for a new parameter for excluding some (annoying) alerts. Will it be possible to have an "exclude blabla" parameter?
At the moment we get (daily) "alerts" which are not very useful or informative, e.g. restarting VDSL-line at nighttimes.

Kudos again,
Joachim

**Comment by martialblog** [comment]
Hi, thanks for the feedback.

I will have a look at it and see if and how we could implement that.

Cheers
Markus

**Comment by airathere** [comment]
Hi martialblog,

yes, this is exactly whats needed, thank you for the implementation!

**Comment by martialblog** [comment]
We just merged the code. I'll see to it that the release is done the next days
